let shopItemsData = [
  {
    id: "Product1",
    name: "Nutritional enhancements",
    price: 28,
    description: "Targeted nutrient therapy for specific health conditions",
    img: "images/photo1.jpg",
  },
  {
    id: "Product2",
    name: "Non-GMO food",
    price: 45,
    description: "Organic food varieties for fostering well-being.",
    img: "images/photo2.jpg",
  },
  {
    id: "Product3",
    name: "Fitness gear",
    price: 15,
    description: "A Home Workout Apparatus.",
    img: "images/photo3.jpg",
  },
  {
    id: "Product4",
    name: "Botanical skincare products",
    price: 250,
    description: "Beauty products formulated with botanical extracts.",
    img: "images/photo4.jpg",
  },
  {
    id: "Product5",
    name: "Instructional books and resources",
    price: 8,
    description: "Stockpile of wellness learning materials.",
    img: "images/photo5.jpg",
  },
  {
    id: "Product6",
    name: "Guilt-free snacks",
    price: 10,
    description: "Assortment of health-conscious snacks (nuts, dried fruits, protein bars)",
    img: "images/photo6.jpg",
  },
  {
    id: "Product7",
    name: "Aroma remedy and botanical oils",
    price: 150,
    description: "The Relaxation Box: Curated products for tranquility.",
    img: "images/photo7.jpg",
  },
  {
    id: "Product8",
    name: "Activewear",
    price: 350,
    description: "Exercise attire for an active lifestyle.",
    img: "images/photo8.jpg",
  },
  {
    id: "Product9",
    name: "Wellness tracker",
    price: 250,
    description: "Intelligent weight scale for health monitoring",
    img: "images/photo9.jpg",
  },
  {
    id: "Product10",
    name: "Herbal medicine",
    price: 40,
    description: "Herbal infusions for wellness.",
    img: "images/photo10.jpg",
  },
  {
    id: "Product11",
    name: "Psychological well-being tools",
    price: 30,
    description: "Contemplative guidance and anxiety-relief equipment.",
    img: "images/photo11.jpg",
  },
  {
    id: "Product12",
    name: "Green living products",
    price: 70,
    description: "Eco-conscious dining tools made of bamboo for personal and environmental balance.",
    img: "images/photo12.jpg",
  },
];
